name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags: '*'
jobs:
  test:
    name: julia ${{ matrix.julia-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['^1.6.0-0',]
        os: ['ubuntu-latest',]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
        if: ${{ matrix.julia-version == '^1.6.0-0' && matrix.os == 'ubuntu-latest' }}
      - uses: codecov/codecov-action@v1
        if: ${{ matrix.julia-version == '^1.6.0-0' && matrix.os == 'ubuntu-latest' }}
        with:
          file: lcov.info
  docs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['^1.6.0-0',]
        os: ['ubuntu-latest',]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Install dependencies
        run: julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.update()'
      - name: Install Makie's dependencies
        run: |
          apt-get -qq update
          apt-get install -y cmake xorg-dev mesa-utils # glfw
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: julia --project=docs --color=yes docs/make.jl
